version: "3.9"

services:
  postgres:
    image: postgres
    hostname: postgres
    environment:
      - POSTGRES_DB=MXL_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - microservices
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 3

  redis:
    image: redis:alpine
    container_name: redis-server
    restart: always
    ports:
      - "6379:6379"
    networks:
      - microservices
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy  # Ensure PostgreSQL is ready before FastAPI starts
      redis:
        condition: service_healthy  # Ensure Redis is ready before FastAPI starts
    environment:
      POSTGRES_HOSTNAME: postgres      # PostgreSQL connection settings
      POSTGRES_PORT: 5432
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: MXL_db
      POSTGRES_USER: postgres
      REDIS_HOST: redis-server         # Redis container name as the host
      REDIS_PORT: 6379                 # Redis default port
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    networks:
      - microservices

volumes:
  postgres_data:

networks:
  microservices:
