"""autogenerate migration

Revision ID: 6a8cd8bc5e8e
Revises: dabb6b011384
Create Date: 2024-09-07 13:29:07.195948

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op



# revision identifiers, used by Alembic.
revision: str = '6a8cd8bc5e8e'
down_revision: Union[str, None] = 'dabb6b011384'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
