"""autogenerate migration

Revision ID: 8f8e8c072490
Revises: e9bfd1a77dc7
Create Date: 2024-09-07 13:16:50.025909

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op



# revision identifiers, used by Alembic.
revision: str = '8f8e8c072490'
down_revision: Union[str, None] = 'e9bfd1a77dc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
