"""autogenerate migration

Revision ID: 9dd3d8ce5758
Revises: 6a8cd8bc5e8e
Create Date: 2024-09-07 13:38:27.982042

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op



# revision identifiers, used by Alembic.
revision: str = '9dd3d8ce5758'
down_revision: Union[str, None] = '6a8cd8bc5e8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
