"""autogenerate migration

Revision ID: dabb6b011384
Revises: 8f8e8c072490
Create Date: 2024-09-07 13:25:48.807489

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op



# revision identifiers, used by Alembic.
revision: str = 'dabb6b011384'
down_revision: Union[str, None] = '8f8e8c072490'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
